DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS categories;

CREATE TABLE `categories` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `courses` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL,
	`url` VARCHAR(255) NOT NULL,
	`platform` VARCHAR(255) NOT NULL,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`finished` TIMESTAMP,
	`complete` BOOLEAN NOT NULL DEFAULT '0',
	`active` BOOLEAN NOT NULL DEFAULT '0',
	`category_id` INT NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `tasks` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`text` VARCHAR(255) NOT NULL,
	`complete` BOOLEAN NOT NULL DEFAULT '0',
	`course_id` INT NOT NULL,
	PRIMARY KEY (`id`)
);

ALTER TABLE `courses` ADD CONSTRAINT `courses_fk0` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE;

ALTER TABLE `tasks` ADD CONSTRAINT `tasks_fk0` FOREIGN KEY (`course_id`) REFERENCES `courses`(`id`) ON DELETE CASCADE;

